spring.application.name=dispenser-la-tienda
spring.profiles.active=local
# Ampliar limite para fotos Base64
server.tomcat.max-http-form-post-size=15MB
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB