spring.application.name=dispenser-la-tienda
spring.profiles.active=local

# Limites de subida (fotos)
server.tomcat.max-http-form-post-size=15MB
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Ruta de almacenamiento
storage.location=C:/Users/Lucas Brandan/IdeaProjects/proyecto-dispenser/uploads

# JWT — cambiá el secret antes de producción
jwt.secret=D1sp3ns3r-L@-T13nd@-JWT-S3cr3t-K3y-2024-Production-Ultra-Secure-256bit
jwt.expiration=86400000
